openapi: 3.0.4
info:
  title: USDA Hardiness Zone
  description: >-
    Hardiness Zone is a simple tool for getting the USDA Plant Hardiness Zone
    for a given zip code
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/hardinesszone:
    get:
      summary: Get Hardiness Zone Data
      description: >-
        Hardiness Zone is a simple tool for getting the USDA Plant Hardiness
        Zone for a given zip code
      operationId: hardinesszone
      parameters:
        - name: zip
          in: query
          schema:
            type: string
          required: true
          description: The zip code to get the USDA Plant Hardiness Zone for
          example: '97201'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  zipCode: '97201'
                  zone: 8b
                  tempRange: 15 to 20
                  zoneTitle: '8b: 15 to 20'
                  details:
                    tempRange: 15째F to 20째F (-9째C to -7째C)
                    description: >-
                      Mild and relatively warm, found in parts of southern U.S.
                      like the Gulf Coast and parts of Texas.
                    plantSurvival: >-
                      A wide range of plants, including many Mediterranean and
                      subtropical varieties.
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
